version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "9090:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/finwise
    depends_on:
      - mongo

  ml-service:
    build: ./ml-service
    ports:
      - "5050:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: